### ISSUE TITLE
Enable blocked keys back immediatly after somehting else has been entered

### ISSUE THREAD

**Issue by ccolorado** [takac/vim-hardtime#27]
There are some use cases when you are ready to move your cursor right after a keystroke but before the hard time timeout has expired.

**Comment by takac** [comment]
Not a valid usecase for this plugin.

**Comment by vegerot** [comment]
I was thinking about something like `list_of_resetting_keys`, but it's every non-movement key.  Essentially, this plugin just stops me from REPEATING bad keys instead of disabling them entirely.  That way I could do `jj5j` (I use `j` once to move down, the second `j` throws an error, so I press `5j` to do it right).  The `5` there resets it.  Or if I want to start a visual selection starting from one line down to the next line I could do `j^Vj`, the `^V` resets it.  Or pretty much anything else, so long as I don't have two j, h, k, l in a row.
